version: '3.3'
services:
  redis:
    container_name: recipy_redis
    image: redis:4.0.10-alpine
    ports:
      - '127.0.0.1:6379:6379'
  postgres:
    container_name: recipy_postgres
    image: postgres:10.4-alpine
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_USER: ${USER}
    volumes:
      - ${PWD}/db:${PWD}/db