MALLOC_ARENA_MAX: '2'

development:
  WEB_CONCURRENCY: '0'

  REDIS_URL: 'redis://localhost:6379/1'

  SMTP_ADDRESS: 'localhost'
  SMTP_PORT: '1025'

  DEFAULT_URL_HOST: '127.0.0.1'

  FACEBOOK_APP_ID: '2316701675039290'
  FACEBOOK_APP_SECRET: '43b315bd52d65c09e7b9d2953d25709e'

test:
  DEFAULT_URL_HOST: 'localhost'
