MALLOC_ARENA_MAX: '2'

FACEBOOK_KEY: '<%= Rails.application.credentials[:omniauth][:facebook][:key] %>'
FACEBOOK_SECRET: '<%= Rails.application.credentials[:omniauth][:facebook][:secret] %>'
TWITTER_KEY: '<%= Rails.application.credentials[:omniauth][:twitter][:key] %>'
TWITTER_SECRET: '<%= Rails.application.credentials[:omniauth][:twitter][:secret] %>'
GOOGLE_KEY: '<%= Rails.application.credentials[:omniauth][:google][:key] %>'
GOOGLE_SECRET: '<%= Rails.application.credentials[:omniauth][:google][:secret] %>'

development:
  WEB_CONCURRENCY: '0'

  REDIS_URL: 'redis://localhost:6379/1'

  SMTP_ADDRESS: 'localhost'
  SMTP_PORT: '1025'

  DEFAULT_URL_HOST: 'localhost'

test:
  DEFAULT_URL_HOST: 'localhost'
