MALLOC_ARENA_MAX: '2'

development:
  WEB_CONCURRENCY: '0'

  REDIS_URL: 'redis://localhost:6379/1'

  SMTP_ADDRESS: 'localhost'
  SMTP_PORT: '1025'

  DEFAULT_URL_HOST: '127.0.0.1'

  FACEBOOK_KEY: '<%= Rails.application.credentials[:development][:omniauth][:facebook][:key] %>'
  FACEBOOK_SECRET: '<%= Rails.application.credentials[:development][:omniauth][:facebook][:secret] %>'
  TWITTER_KEY: '<%= Rails.application.credentials[:development][:omniauth][:twitter][:key] %>'
  TWITTER_SECRET: '<%= Rails.application.credentials[:development][:omniauth][:twitter][:secret] %>'
  GOOGLE_KEY: '<%= Rails.application.credentials[:development][:omniauth][:google][:key] %>'
  GOOGLE_SECRET: '<%= Rails.application.credentials[:development][:omniauth][:google][:secret] %>'

test:
  DEFAULT_URL_HOST: 'localhost'
