default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: recipy_development

test:
  <<: *default
  database: recipy_test

production:
  url: <%= ENV['DATABASE_URL'] %>
