:verbose: <%= ENV.fetch('SIDEKIQ_VERBOSE', false) %>
:timeout: <%= ENV.fetch('SIDEKIQ_TIMEOUT', 30) %>
:concurrency: <%= ENV.fetch('SIDEKIQ_CONCURRENCY', 10) %>

:queues:
  - [critical, 4]
  - [mailers, 4]
  - [default, 2]
  - [low, 1]
  - [sentries, 1]
